name: super_enum_generator
description: Dev-dependency to generate sealed classes and when statements together with the super_enum.dart package.
version: 0.7.0
homepage: https://github.com/Abdalqader27/super_enum_generator.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  # Specify a specific version or a version constraint
  # for "super_enum" before publishing the package.
#  super_enum: ^0.5.0

  super_enum:
    git:
      url: https://github.com/Abdalqader27/super_enum.git
      ref: "0.7.0"


  source_gen: ^1.0.5
#  analyzer: '>=1.3.0 <2.0.0'
#  build: '>=2.0.0 <3.0.0'
  code_builder: ^4.1.0
  dart_style: ^2.0.3

dev_dependencies:
  test: ^1.17.10
  build_runner: ^2.0.6
  source_gen_test: ^1.0.0